apiVersion: apps/v1
kind: Deployment

metadata:
  name: hello-nginx
  namespace: hello-world

spec:
  replicas: 1

  selector:
    matchLabels:
      app: hello-nginx

  template:

    metadata:
      labels:
        app: hello-nginx

    spec:

      containers:

      - name: nginx

        image: nginx:latest

        ports:
        - containerPort: 80

        readinessProbe:
          httpGet:
            path: /
            port: 80

        livenessProbe:
          httpGet:
            path: /
            port: 80

        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html

      volumes:
      - name: html-volume
        configMap:
          name: nginx-html
