- name: Configure kubeconfig
  run: |
    mkdir -p ~/.kube

    echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > ~/.kube/config

    chmod 600 ~/.kube/config

- name: Verify Cluster
  run: |
    kubectl version
    kubectl cluster-info
    kubectl get nodes

- name: Deploy Namespace
  run: kubectl apply -f kubernetes/namespace.yaml

- name: Deploy App
  run: kubectl apply -f kubernetes/
